# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Namit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Namit
  pod 'SnapKit', '~> 4.0.0'
  pod 'lottie-ios'
  
  target 'NamitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NamitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
